# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(465, 263)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.rasterLineEdit = QtWidgets.QLineEdit(Dialog)
        self.rasterLineEdit.setObjectName("rasterLineEdit")
        self.gridLayout.addWidget(self.rasterLineEdit, 0, 1, 1, 1)
        self.rasterButton = QtWidgets.QPushButton(Dialog)
        self.rasterButton.setObjectName("rasterButton")
        self.gridLayout.addWidget(self.rasterButton, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.outputDirLineEdit = QtWidgets.QLineEdit(Dialog)
        self.outputDirLineEdit.setObjectName("outputDirLineEdit")
        self.gridLayout.addWidget(self.outputDirLineEdit, 2, 1, 1, 1)
        self.outputDirButton = QtWidgets.QPushButton(Dialog)
        self.outputDirButton.setObjectName("outputDirButton")
        self.gridLayout.addWidget(self.outputDirButton, 3, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Raster File"))
        self.rasterButton.setText(_translate("Dialog", "Browse…"))
        self.label_2.setText(_translate("Dialog", "Output Directory"))
        self.outputDirButton.setText(_translate("Dialog", "Browse…"))
